package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"wdi/internal/interface/graph"
	"wdi/internal/interface/graph/model"
)

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello, world!", nil
}

// GetIndicatorList is the resolver for the GetIndicatorList field.
func (r *queryResolver) GetIndicatorList(ctx context.Context, search string, limit int32, offset int32) ([]*model.IndicatorList, error) {
	return r.IndicatorUC.ListIndicators(search, limit, offset)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
