package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"wdi/graph/model"
)

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello from Graphql!", nil
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context, search *string, region *string, incomeGroup *string, limit *int32, offset *int32) ([]*model.Country, error) {
	lim := int32(10)
	off := int32(0)
	if limit != nil {
		lim = int32(*limit)
	}
	if offset != nil {
		off = int32(*offset)
	}

	return r.CountryUC.GetAllCountries(search, region, incomeGroup, lim, off)
}

// Country is the resolver for the country field.
func (r *queryResolver) Country(ctx context.Context, code string) (*model.Country, error) {
	country, err := r.CountryUC.FindByCode(code)
	if err != nil {
		return nil, err
	}

	return country, nil
}

// Regions is the resolver for the regions field.
func (r *queryResolver) Regions(ctx context.Context) ([]string, error) {
	return r.CountryUC.ListRegions()
}

// IncomeGroups is the resolver for the incomeGroups field.
func (r *queryResolver) IncomeGroups(ctx context.Context) ([]string, error) {
	return r.CountryUC.ListIncomeGroups()
}

// CountryCount is the resolver for the countryCount field.
func (r *queryResolver) CountryCount(ctx context.Context) (int32, error) {
	nb, err := r.CountryUC.CountCountries()
	if err != nil {
		return 0, err
	}
	return int32(nb), nil
}

// RegionCounts is the resolver for the regionCounts field.
func (r *queryResolver) RegionCounts(ctx context.Context) ([]*model.RegionCount, error) {
	return r.CountryUC.CountByRegion()
}

// CountriesByCodes is the resolver for the countriesByCodes field.
func (r *queryResolver) CountriesByCodes(ctx context.Context, codes []string) ([]*model.Country, error) {
	return r.CountryUC.GetCountriesByCodes(codes)
}

// AutocompleteCountries is the resolver for the autocompleteCountries field.
func (r *queryResolver) AutocompleteCountries(ctx context.Context, prefix string, limit *int32) ([]*model.Country, error) {
	lim := int(10)
	if limit != nil {
		lim = int(*limit)
	}

	return r.CountryUC.GetAutocompleteCountries(prefix, lim)
}

// Indicators is the resolver for the indicators field.
func (r *queryResolver) Indicators(ctx context.Context) ([]*model.Indicator, error) {
	return r.IndicatorUC.ListIndicators()
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
