// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Indicator struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type IndicatorBarRaceRow struct {
	Year    int32   `json:"year"`
	Country string  `json:"country"`
	Value   float64 `json:"value"`
}

type IndicatorYear struct {
	Year int32 `json:"year"`
}

type Query struct {
}
