// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IndicatorList struct {
	Indicatorcode string `json:"indicatorcode"`
	Indicatorname string `json:"indicatorname"`
}

type Query struct {
}
