// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	CountryCode  string `json:"CountryCode"`
	ShortName    string `json:"ShortName"`
	TableName    string `json:"TableName"`
	LongName     string `json:"LongName"`
	Alpha2Code   string `json:"Alpha2Code"`
	CurrencyUnit string `json:"CurrencyUnit"`
	SpecialNotes string `json:"SpecialNotes"`
	Region       string `json:"Region"`
	IncomeGroup  string `json:"IncomeGroup"`
}

type Query struct {
}

type RegionCount struct {
	Region string `json:"region"`
	Count  int32  `json:"count"`
}
